package org.yangdai.kori.data.repository

import kotlinx.coroutines.flow.Flow
import org.yangdai.kori.data.local.dao.SnapshotDao
import org.yangdai.kori.data.local.entity.SnapshotEntity
import org.yangdai.kori.domain.repository.SnapshotRepository

class SnapshotRepositoryImpl(private val dao: SnapshotDao) : SnapshotRepository {
    override suspend fun insertSnapshot(snapshot: SnapshotEntity): Long {
        return dao.insertSnapshot(snapshot)
    }

    override suspend fun deleteSnapshot(snapshot: SnapshotEntity) {
        dao.deleteSnapshotById(snapshot.id)
    }

    override suspend fun deleteSnapshotById(id: Long) {
        dao.deleteSnapshotById(id)
    }

    override suspend fun deleteSnapshotsByNoteId(noteId: String) {
        dao.deleteSnapshotsByNoteId(noteId)
    }

    override suspend fun cleanupOldSnapshots(noteId: String, limit: Int) {
        dao.deleteExcessSnapshots(noteId, limit)
    }

    override suspend fun getSnapshotById(id: String): SnapshotEntity? {
        return dao.getSnapshotById(id)
    }

    override fun getSnapshotsByNoteIdFlow(noteId: String): Flow<List<SnapshotEntity>> {
        return dao.getSnapshotsByNoteIdFlow(noteId)
    }

    override suspend fun saveSnapshotForNote(noteId: String, title: String, content: String) {
        // Create a new snapshot with the provided data
        val snapshot = SnapshotEntity(
            id = 0, // Will be auto-generated by Room
            noteId = noteId,
            title = title,
            content = content
        )

        // Insert the new snapshot
        dao.insertSnapshot(snapshot)

        // Clean up old snapshots to maintain the limit (default 5)
        cleanupOldSnapshots(noteId, 5)
    }
}